import { serve } from '@hono/node-server'
import { serveStatic } from '@hono/node-server/serve-static'
import { Hono } from 'hono'
import workerApp from './worker'
import { config } from 'dotenv'
import { readFile } from 'fs/promises'

// Load environment variables
config()

const port = Number(process.env.PORT) || 3000

const app = new Hono()

// 1. Mount API Routes (from worker.ts)
// Note: workerApp handles /api/* routes
app.route('/', workerApp)

// 2. Serve Static Files (Frontend)
// This serves files from the 'dist' directory generated by Vite
app.use('/*', serveStatic({ root: './dist' }))

// 3. SPA Fallback
// For any other route not handled by API or static files, serve index.html
app.get('*', async (c) => {
  // Don't intercept API 404s
  if (c.req.path.startsWith('/api')) {
    return c.notFound()
  }
  try {
    const indexHtml = await readFile('./dist/index.html', 'utf-8')
    return c.html(indexHtml)
  } catch (e) {
    return c.text('Frontend build not found. Please run `npm run build` first.', 404)
  }
})

console.log(`Server is running on port ${port}`)

serve({
  fetch: app.fetch,
  port
})
